### ISSUE TITLE
Expand environment variables in manifest file

### ISSUE THREAD

**Issue by ewbankkit** [wascc/wascc-host#19]
I'd like to be able to expand environment variables in the host's manifest file.
For example:

```yaml
---
actors:
  - "${ACTOR}"

capabilities:
  - libprovider.so

config:
  - actor: "M..."
    capability: "custom:capability"
    values:
      SOME_KEY: "${SOME_VALUE}"
```
